### ISSUE TITLE
Guardar Resultados

### ISSUE THREAD

**Issue by Ca-moes** [Ca-moes/feup-plog-proj-2#3]
@skdGT 
- Ir ao branch main
- abrir SICStus
- Mudar working directory para pasta `Resultados_save_all`
- Consult de `goldstar.pl`
- `save_all` e deixar a magia acontecer

Os saves estão por ordem crescente de resultados, os primeiros 3 devem demorar mas mesmo assim ficam com tempos razoáveis, O primeiro demorou-me 3 minutos, o segundo deve demorar mais, e o terceiro vai dar 1.04m de resultados. Os 2 últimos: `print_unrestricted_all_sol` e `print_all_comb` podem maybe ocupar os tais 20gb como da outra vez, se isso acontecer então é para desistir destes, dá-se 30 mins ao `print_unrestricted_all_sol` e se estiver a começar a ocupar muito então cancela e fica-se com os 3 primeiros.

Fiz o predicado `save_all` para não teres muito trabalho mas se quiseres podes abrir 5 consolas de sicstus e fazer cada `save()` numa delas para fazer em paralelo.

**Comment by goncaloacteixeira** [comment]
okay, quinta feira estou no porto e meto o meu bebé a correr isso

**Comment by Ca-moes** [comment]
@skdGT está tudo pronto. Quando puderes vai ao branch https://github.com/Ca-moes/feup-plog-proj-2/tree/dimensional, mudas o working directory para a pasta `results`, compilas e corres o programa com `save_all`:
```prolog
save_all:-
    save_group(3),
    save_group(4),
    save_group(5),
    write('\nAll Finished\n').
```
isto vai guardar todas as opções para estrelas de 3,4 e 5 pontas, se vires que for rápido adicionas aí `save_group(6)`, `save_group(7)`, etc até te fartares. Os ficheiros não devem ficar absurdamente grandes com as novas restrições na divisão.

No final tira print ao que aparece na consola, assim fica mais fácil de ver quanto tempo é que cada um demorou.

Abreijos
